name: Python CI/CD

on:
  push:
    branches:
      - main  # Rulează pe push-uri către ramura 'main'
  pull_request:
    branches:
      - main  # Rulează pe pull request-uri către ramura 'main'

jobs:
  # Jobul pentru Continuous Integration (CI)
  test:
    runs-on: ubuntu-latest  # Rulează pe un sistem Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Face checkout la codul repository-ului

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Setează versiunea de Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Instalează dependențele din requirements.txt

      - name: Run tests
        run: |
          pytest  # Rulează testele automatizate cu pytest

  # Jobul pentru Continuous Deployment (CD) pe Google Cloud
  deploy:
    needs: test  # Rulează doar dacă job-ul de test a trecut cu succes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to staging
        run: |
          echo "Deploying application to staging environment"

